### ISSUE TITLE
EmeraldEnchants2 Not appearing in GUI

### ISSUE THREAD

**Issue by EchocallingEarth** [TheBusyBiscuit/EmeraldEnchants2#9]
1 - Disappears and reappears at random from GUI
2 - When available does not allow for return to main GUI option no back book to click on.
No errors in console

Install EmeraldEnchants2 along with SF and CSLIb. - Restart Server -
1 - Open SF Cheats Look for EmeraldEnchants (not visible).
2 - Open SF Cheats Look for EmeraldEnchants (visible) click to access and then attempt to return to main GUI (no option or return to book provided)
![missing emeraldenchant2](https://user-images.githubusercontent.com/47970978/70933951-dbf13000-200a-11ea-9d0f-2935ce899106.PNG)

Should be visible in GUI at all times
Should have a back to main GUI feature like other SF features do.

No error log or errors given in console - Pastebin not required

sf versions
![sf versions](https://user-images.githubusercontent.com/47970978/70934014-f75c3b00-200a-11ea-98f9-36e3bc78f09a.PNG)

1.14.4
vDEV - 637 ( git aa9652c )
vDEV - 78 ( git 199e1b1e )

**Comment by EchocallingEarth** [comment]
Additional note I am unable to pull up the EmeraldEnchants GUI section to show the lack of back-book or back option.  There for at this time I can not provide a picture or screen clip of this issue. I will however continue to attempt to have EmerldEnchants show and grab the required screen shot.

Returning to edit to show the EnmeraldEnchants GUI lacking the backbook or back option to return to the SF GUI
![emeraldenchants2 GUI](https://user-images.githubusercontent.com/47970978/70968808-41273e80-2068-11ea-978d-f4cd65141d71.PNG)

**Comment by EchocallingEarth** [comment]
Continued in depth testing finds that /sf guide shows the EmeraldEnchants in the GUI. While the use of /sf cheat does not, as noted above. 

![not missing emeraldenchant2](https://user-images.githubusercontent.com/47970978/70968634-be05e880-2067-11ea-90af-3e78c7ef90d2.PNG)

I am not sure if this additional information will help in diagnosing the issue but I do hope it helps.

**Comment by EchocallingEarth** [comment]
_Adding this here - but unsure if related or requires a separate ticket. If a separate ticket someone please let me know and I will open one asap._
This is an error log section that I get in the console for **EmeraldEnchants**

[13:15:55 ERROR]: Could not pass event BlockBreakEvent to EmeraldEnchants vDEV - 5 (git 6adbbb87)
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.EntityItem.setItemStack(EntityItem.java:429) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.EntityItem.<init>(EntityItem.java:41) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItem(CraftWorld.java:700) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.dropItemNaturally(CraftWorld.java:717) ~[patched_1.14.4.jar:git-Paper-234]
        at me.mrCookieSlime.EmeraldEnchants.listeners.EnchantmentActionListener.onDig(EnchantmentActionListener.java:96) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor661.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-234]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-234]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:306) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:265) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:239) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[?:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-234]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by TheBusyBiscuit** [comment]
EmeraldEnchants is not an Addon to Slimefun, Slimefun simply integrates EE's guide into Slimefun's.
And there isn't a way to cheat in the items from EmeraldEnchants because it doesn't have any, it only adds Enchantments, so it is completely intentional that it doesn't appear in /sf cheat

Make a seperate issue for the error though and use pastebin for reporting errors.
